// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetDiskWriteSpeed(arg1:number):Promise<number>;

export function GetProcesses():Promise<Array<main.Process>>;

export function SetContext(arg1:context.Context):Promise<void>;
