// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiskWriteSpeed(arg1) {
  return window['go']['main']['DiskManager']['GetDiskWriteSpeed'](arg1);
}

export function GetProcesses() {
  return window['go']['main']['DiskManager']['GetProcesses']();
}

export function SetContext(arg1) {
  return window['go']['main']['DiskManager']['SetContext'](arg1);
}
