// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetectInterface() {
  return window['go']['main']['NetworkManager']['AutoDetectInterface']();
}

export function GetIOStatByMac(arg1) {
  return window['go']['main']['NetworkManager']['GetIOStatByMac'](arg1);
}

export function GetInterfaceByMac(arg1) {
  return window['go']['main']['NetworkManager']['GetInterfaceByMac'](arg1);
}

export function GetInterfaceDownloadSpeed(arg1) {
  return window['go']['main']['NetworkManager']['GetInterfaceDownloadSpeed'](arg1);
}

export function GetInterfaces() {
  return window['go']['main']['NetworkManager']['GetInterfaces']();
}

export function SetContext(arg1) {
  return window['go']['main']['NetworkManager']['SetContext'](arg1);
}
